#███████╗███╗░░░███╗░██████╗████████╗░█████╗░███████╗███████╗░██╗░░░░░░░██╗░█████╗░██████╗░██╗░░██╗███████╗██████╗░███████╗███████╗
#██╔════╝████╗░████║██╔════╝╚══██╔══╝██╔══██╗██╔════╝██╔════╝░██║░░██╗░░██║██╔══██╗██╔══██╗██║░██╔╝██╔════╝██╔══██╗██╔════╝██╔════╝
#█████╗░░██╔████╔██║╚█████╗░░░░██║░░░███████║█████╗░░█████╗░░░╚██╗████╗██╔╝██║░░██║██████╔╝█████═╝░█████╗░░██████╔╝█████╗░░█████╗░░
#██╔══╝░░██║╚██╔╝██║░╚═══██╗░░░██║░░░██╔══██║██╔══╝░░██╔══╝░░░░████╔═████║░██║░░██║██╔══██╗██╔═██╗░██╔══╝░░██╔══██╗██╔══╝░░██╔══╝░░
#██║░░░░░██║░╚═╝░██║██████╔╝░░░██║░░░██║░░██║██║░░░░░██║░░░░░░░╚██╔╝░╚██╔╝░╚█████╔╝██║░░██║██║░╚██╗██║░░░░░██║░░██║███████╗███████╗
#╚═╝░░░░░╚═╝░░░░░╚═╝╚═════╝░░░░╚═╝░░░╚═╝░░╚═╝╚═╝░░░░░╚═╝░░░░░░░░╚═╝░░░╚═╝░░░╚════╝░╚═╝░░╚═╝╚═╝░░╚═╝╚═╝░░░░░╚═╝░░╚═╝╚══════╝╚══════╝
# Связь с разработчиком:
# VK - @feymer31
# TG - @feymerwtf
settings:

  commands-on: # Команды, которые выполняются, когда игрок включает режим патруля
    - "lp user %player% permission set litebans.ban true"
    - "lp user %player% permission set litebans.mute true"
    - "lp user %player% permission set litebans.kick true"
  commands-off: # Команды, которые выполняются, когда игрок выключает режим патруля
    - "lp user %player% permission set litebans.ban false"
    - "lp user %player% permission set litebans.mute false"
    - "lp user %player% permission set litebans.kick false"
  disable-entity-damage: true # Выключить ли урон по энтити, когда игрок находится в режиме патруля?
  disable-block-place: true # Выключить ли урон по энтити, когда игрок находится в режиме патруля?
  disable-block-break: true # Выключить ли урон по энтити, когда игрок находится в режиме патруля?

messages:

  no-permission: "&cНе хватает прав!" # Сообщение, когда у игрока нет прав
  reload: "&fВы перезагрузили плагин!" # Сообщение, когда перезагружается конфиг
  help: # Сообщение, когда игрок вводит команду неправильно
    - "&fПомощь по плагину &6fmStaffWork&7:"
    - ""
    - "&6/staffwork on &7- &fвключить режим патруля"
    - "&6/staffwork off &7- &fвыключить режим патруля"
    - "&6/staffwork stats &7- &fузнать свою статистику"
    - "&6/staffwork stats &7(&6игрок&7) - &fузнать статистику игрока"
    - "&6/staffwork stats all &7- &fузнать статистику игроков"
    - "&6/fmstaffwork reload &7- &fперезагрузить плагин"
    - ""

  on-work: "&fВы включили режим патруля!" # Сообщение, когда игрок включает режим патруля
  off-work: "&fВы выключили режим патруля!" # Сообщение, когда игрок выключает режим патруля
  on-all: "&fИгрок &6%player% &fвошел в режим патруля!" # Сообщение всему серверу, когда игрок включает режим патруля
  off-all: "&fИгрок &6%player% &fвышел из режима патруля!" # Сообщение всему серверу, когда игрок выключает режим патруля
  stats: # Сообщение со статистикой игрока
    - ""
    - "&fСтатистика игрока &6%player%&7:"
    - "&fНаиграно: &6%time%"
    - "&fБанов: &6%bans%"
    - "&fМутов: &6%mutes%"
    - "&fКиков: &6%kicks%"
    - ""
  wasnot-working: "&fИгрок не работал!" # Сообщение, когда игрок не работал
  not-working: "&fВы не находитесь в режиме патруля!" # Сообщение, когда игрок не находится в режиме патруля
  already-working: "&fВы уже находитесь в режиме патруля!" # Сообщение, когда игрок уже находится в режиме патруля
  data-null: "&fДанные не найдены!" # Сообщение, когда данные о работе не найдены
  entity-damage-disabled: "&fВы не можете наносить урон, когда находитесь в режиме патруля!" # Сообщение, когда игрок наносит урон по энтити, когда находится в режиме патруля
  block-place-disabled: "&fВы не можете ставить блоки, когда находитесь в режиме патруля!" # Сообщение, когда игрок ставит блок, когда находится в режиме патруля
  block-break-disabled: "&fВы не можете ломать блоки, когда находитесь в режиме патруля!" # Сообщение, когда игрок ломает блок, когда находится в режиме патруля